M48
; DRILL file {KiCad 8.0.6} date 2025-03-13T06:25:39-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-13T06:25:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
%
G90
G05
T1
X73.99Y-86.63
X73.99Y-92.41
T2
X181.3Y-72.65
X204.0Y-72.65
M30
